const fields = [
  {
    name: "first_name",
    label: "First Name",
    placeholder: "Enter your first name",
    required: true,
    type: "text",
    half: true,
  },
  {
    name: "last_name",
    label: "Last Name",
    placeholder: "Enter your last name",
    required: true,
    type: "text",
    half: true,
  },
  {
    name: "email",
    label: "Email Address",
    placeholder: "Enter your email address",
    required: true,
    type: "email",
  },
  {
    name: "phone",
    label: "Phone Number",
    placeholder: "Enter your phone number",
    required: true,
    type: "tel",
  },
  {
    select: true,
    name: "country",
    label: "Country / Region",
    placeholder: "Choose your country",
    required: true,
    dataKey: "countryOptions",
  },
  {
    name: "address",
    label: "Address",
    placeholder: "House number and street name, apartment, unit, etc.",
    required: true,
    type: "text",
  },
  {
    name: "city",
    label: "City",
    placeholder: "Enter your city",
    required: true,
    type: "text",
  },
  {
    select: true,
    name: "state",
    label: "State",
    placeholder: "Choose your state",
    required: true,
    dataKey: "stateOptions",
    half: true,
  },
  {
    name: "zipcode",
    label: "Postcode / zip",
    placeholder: "Enter your postcode",
    required: true,
    type: "text",
    half: true,
  },
];

export default fields;
